### ISSUE TITLE
Automate Habitica v0.29.22 failed

### ISSUE THREAD

**Issue by KevinTyrrell5381** [bumbleshoot/automate-habitica#13] opened 2023-03-31 13:53 UTC
**What is the bug?**
After installing Automate Habitica v0.29.22 yesterday, received "Automate Habitica v0.29.22 failed!" email messages overnight.

**Additional context**
I installed latest version of Automate Habitica: v0.29.22 yesteday (3/30/2023).

Errors are of 3 different types:

Exception: Service invoked too many times for one day: urlfetch.
    at fetch (global:576:32)
    at getUser (global:720:14) 
    at castEarthquake (automations/castMageSkills:55:7)
    at useExcessMana (global:532:5)
    at processQueue (global:388:11)
    at onTrigger (global:27:5)
    at __GS_INTERNAL_top_function_call__.gs:1:8 

Exception: Service invoked too many times for one day: urlfetch.
    at fetch (global:576:32)
    at getContent (global:837:17) 
    at notifyQuestEnded (automations/notifyQuestEnded:20:3)
    at processQueue (global:353:11)
    at doPost (global:88:5)
    at __GS_INTERNAL_top_function_call__.gs:1:8 

Exception: Service invoked too many times for one day: urlfetch.
    at fetch (global:576:32)
    at getUser (global:720:14)
    at processTrigger (global:115:62)
    at onTrigger (global:26:5)
    at __GS_INTERNAL_top_function_call__.gs:1:8 

**How often does this happen?**
I received 59 Automate Habitica failed messages in the past day.

**Script version**
v0.29.22

**Script settings**
```
const AUTO_CRON = false; // true or false

const AUTO_ACCEPT_QUEST_INVITES = false;

const FORCE_START_QUESTS = false; // party leaders only
const FORCE_START_QUESTS_AFTER_HOURS = 1; // eg. if set to 1, quests will force start after 1h
const NOTIFY_MEMBERS_EXCLUDED_FROM_QUEST = true;

const AUTO_INVITE_GOLD_QUESTS = false;
const AUTO_INVITE_UNLOCKABLE_QUESTS = false;
const AUTO_INVITE_PET_QUESTS = false;
const AUTO_INVITE_HOURGLASS_QUESTS = false;
const PM_WHEN_OUT_OF_QUEST_SCROLLS = true;

const NOTIFY_ON_QUEST_END = false;

const AUTO_CAST_SKILLS = true;

const AUTO_PAUSE_RESUME_DAMAGE = false;
const MAX_PLAYER_DAMAGE = 20;
const MAX_PARTY_DAMAGE = 5;

const AUTO_ALLOCATE_STAT_POINTS = false;
const STAT_TO_ALLOCATE = "int"; // str, int, con, per

const AUTO_PURCHASE_GEMS = false; // subscribers only

const AUTO_PURCHASE_ARMOIRES = true;
const RESERVE_GOLD = 50000;

const AUTO_SELL_EGGS = false;
const RESERVE_EGGS = 999;

const AUTO_SELL_HATCHING_POTIONS = false;
const RESERVE_HATCHING_POTIONS = 999;

const AUTO_SELL_FOOD = false;
const RESERVE_FOOD = 999;

const AUTO_HATCH_FEED_PETS = true;
const ONLY_USE_DROP_FOOD = true;

const HIDE_PARTY_NOTIFICATIONS = false;
const HIDE_ALL_GUILD_NOTIFICATIONS = false;
const HIDE_NOTIFICATIONS_FROM_SPECIFIC_GUILDS = [ // only used if HIDE_ALL_GUILD_NOTIFICATIONS is false
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // enter a guild ID between the quotes to hide notifications from that guild
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" // repeat for as many guilds as you want
]
```

**Comment by bumbleshoot** [comment] 2023-04-05 01:09
Hi! This is a duplicate of #10. I will close this issue so we can continue the conversation there.

**Closed by bumbleshoot** 2023-04-05 01:09 UTC
Labels: bug
