### ISSUE TITLE
Auto inn with no quest or damage pending

### ISSUE THREAD

**Issue by blackcatsnow** [bumbleshoot/automate-habitica#17] opened 2023-04-24 15:23 UTC
**What is the bug?**
The script automatically checks me into the in even though there is not a quest running therefore no damage pending. 

**Additional context**
If I check myself out it just puts me right back in.

**How often does this happen?**
Several times a day

**Script version**
0.29.32

**Script settings**
```
const AUTO_CRON = true; // true or false

const AUTO_ACCEPT_QUEST_INVITES = true;

const FORCE_START_QUESTS = true; // party leaders only
const FORCE_START_QUESTS_AFTER_HOURS = 24; // eg. if set to 1, quests will force start after 1h
const NOTIFY_MEMBERS_EXCLUDED_FROM_QUEST = true;

const AUTO_INVITE_GOLD_QUESTS = false;
const AUTO_INVITE_UNLOCKABLE_QUESTS = false;
const AUTO_INVITE_PET_QUESTS = false;
const AUTO_INVITE_HOURGLASS_QUESTS = false;
const PM_WHEN_OUT_OF_QUEST_SCROLLS = true;

const NOTIFY_ON_QUEST_END = true;

const AUTO_CAST_SKILLS = true;

const AUTO_PAUSE_RESUME_DAMAGE = false;
const MAX_PLAYER_DAMAGE = 20;
const MAX_PARTY_DAMAGE = 5;

const AUTO_ALLOCATE_STAT_POINTS = false;
const STAT_TO_ALLOCATE = "int"; // str, int, con, per

const AUTO_PURCHASE_GEMS = true; // subscribers only

const AUTO_PURCHASE_ARMOIRES = false;
const RESERVE_GOLD = 50000;

const AUTO_SELL_EGGS = false;
const RESERVE_EGGS = 999;

const AUTO_SELL_HATCHING_POTIONS = false;
const RESERVE_HATCHING_POTIONS = 999;

const AUTO_SELL_FOOD = false;
const RESERVE_FOOD = 999;

const AUTO_HATCH_FEED_PETS = true;
const ONLY_USE_DROP_FOOD = true;

const HIDE_PARTY_NOTIFICATIONS = false;
const HIDE_ALL_GUILD_NOTIFICATIONS = false;
const HIDE_NOTIFICATIONS_FROM_SPECIFIC_GUILDS = [ // only used if HIDE_ALL_GUILD_NOTIFICATIONS is false
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // enter a guild ID between the quotes to hide notifications from that guild
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" // repeat for as many guilds as you want
]
```

**Comment by bumbleshoot** [comment] 2023-05-03 00:38
Hi @blackcatsnow, the script should check you into the Inn if your pending damage is greater than `MAX_PLAYER_DAMAGE` or `MAX_PARTY_DAMAGE`, and you are either:
1. fighting a boss, or
2. invited to a boss quest.
In these cases where you are checked into the Inn with no boss quest running, has criteria 2 (invited to a boss quest) been met?

**Comment by blackcatsnow** [comment] 2023-05-03 00:45
Hey! I believe it is usually when there is a pending quest and I have already accepted the invite.

**Comment by bumbleshoot** [comment] 2023-05-03 01:12
Great! Sounds like it is working as intended. Once you are invited to a boss quest, the quest could start & finish within seconds, so the script puts you in the Inn (if your pending damage is greater than `MAX_PLAYER_DAMAGE` or `MAX_PARTY_DAMAGE`) in anticipation of that happening.

**Closed by bumbleshoot** 2023-05-03 01:12 UTC
Labels: bug

**Comment by blackcatsnow** [comment] 2023-05-03 01:16
But my auto pause damage is set to false?

**Comment by bumbleshoot** [comment] 2023-05-03 01:37
@blackcatsnow Ok, this is a separate issue :) can you please submit a new bug report for it? thanks!
